### ISSUE TITLE
Formula.sha1 is deprecated

### ISSUE THREAD

**Issue by stefancrain** [acrogenesis/macchanger#6]
System info
```
$ brew config
HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: a9ab066654913a369cefccd13284d9d912dd5bb9
Last commit: 63 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 7a1ca5ed8fdc2f30887dc7cdaece203d7408588c
Core tap last commit: 47 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 7.3 build 703
Git: 2.9.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_92, 1.8.0_74, 1.8.0_60, 1.7.0_79
OS X: 10.11.6-x86_64
Xcode: 7.3.1
CLT: 7.3.1.0.1.1461711523
X11: N/A
```

Error
````
$ brew install acrogenesis/macchanger/macchanger
==> Tapping acrogenesis/macchanger
Cloning into '/usr/local/Library/Taps/acrogenesis/homebrew-macchanger'...
remote: Counting objects: 5, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 5 (delta 0), reused 5 (delta 0), pack-reused 0
Unpacking objects: 100% (5/5), done.
Checking connectivity... done.
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/acrogenesis/homebrew-macchanger/macchanger.rb:7:in `<class:Macchanger>'
Please report this to the acrogenesis/macchanger tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/acrogenesis/homebrew-macchanger/macchanger.rb:7:in `<class:Macchanger>'
Please report this to the acrogenesis/macchanger tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/acrogenesis/homebrew-macchanger/macchanger.rb:7:in `<class:Macchanger>'
Please report this to the acrogenesis/macchanger tap!

Tapped 1 formula (29 files, 21.8K)
==> Installing macchanger from acrogenesis/macchanger
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/acrogenesis/homebrew-macchanger/macchanger.rb:7:in `<class:Macchanger>'
Please report this to the acrogenesis/macchanger tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/acrogenesis/homebrew-macchanger/macchanger.rb:7:in `<class:Macchanger>'
Please report this to the acrogenesis/macchanger tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/acrogenesis/homebrew-macchanger/macchanger.rb:7:in `<class:Macchanger>'
Please report this to the acrogenesis/macchanger tap!

==> Downloading https://github.com/acrogenesis/macchanger/archive/v1.2.tar.gz
Already downloaded: /Users/##/Library/Caches/Homebrew/macchanger-1.2.tar.gz
Warning: Calling Pathname#sha1 is deprecated!
Use Pathname#sha256 instead.
/usr/local/Library/Homebrew/extend/pathname.rb:320:in `verify_checksum'

🍺  /usr/local/Cellar/macchanger/1.2: 4 files, 4.8K, built in 0 seconds
```

**Comment by acrogenesis** [comment]
fixed, thanks

**Comment by stefancrain** [comment]
thanks @acrogenesis
